{{-- Contract Report - Signature Section --}}
<div class="signature-section">
    <h2>Signatures</h2>
    <p>IN WITNESS WHEREOF, the parties have executed this Agreement as of the Contract Date first above written.</p>
    
    <div class="signature-grid">
        <div class="signature-block">
            <h4>Service Provider</h4>
            
            <div class="signature-line">
                <div class="signature-line-label">Signature</div>
                <div class="signature-line-value"></div>
            </div>
            
            <div class="signature-line">
                <div class="signature-line-label">Printed Name</div>
                <div class="signature-line-value">{{ isset($providerName) ? $providerName : '___________________________' }}</div>
            </div>
            
            <div class="signature-line">
                <div class="signature-line-label">Title</div>
                <div class="signature-line-value">{{ isset($providerTitle) ? $providerTitle : '___________________________' }}</div>
            </div>
            
            <div class="signature-line">
                <div class="signature-line-label">Date</div>
                <div class="signature-line-value">___________________________</div>
            </div>
        </div>
        
        <div class="signature-block">
            <h4>Client</h4>
            
            <div class="signature-line">
                <div class="signature-line-label">Signature</div>
                <div class="signature-line-value"></div>
            </div>
            
            <div class="signature-line">
                <div class="signature-line-label">Printed Name</div>
                <div class="signature-line-value">{{ $recipientName ?? '___________________________' }}</div>
            </div>
            
            <div class="signature-line">
                <div class="signature-line-label">Title</div>
                <div class="signature-line-value">{{ isset($recipientTitle) ? $recipientTitle : '___________________________' }}</div>
            </div>
            
            <div class="signature-line">
                <div class="signature-line-label">Date</div>
                <div class="signature-line-value">___________________________</div>
            </div>
        </div>
    </div>
</div>

{{-- Footer --}}
<div class="contract-footer">
    Generated by ArchitGrid Intelligence Node v1.0.4
</div>
