{{-- CV Resume - Modern Layout (Sidebar) --}}
{{-- Modern Sidebar Layout --}}
<div class="cv-sidebar">
    <div class="mb-8 text-center">
        @if(!empty($profilePhotoUrl))
            <img src="{{ $profilePhotoUrl }}" style="width: 140px; height: 140px; object-fit: cover; border-radius: 50%; border: 4px solid white; box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);">
        @elseif(!empty($profile_photo_url))
            <img src="{{ $profile_photo_url }}" style="width: 140px; height: 140px; object-fit: cover; border-radius: 50%; border: 4px solid white; box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);">
        @elseif(!empty($logoUrl))
            <img src="{{ $logoUrl }}" style="width: 80px; height: 80px; object-fit: contain; opacity: 0.8;">
        @else
            <div style="width: 100px; height: 100px; background: #e2e8f0; border-radius: 50%; margin: 0 auto; display: flex; align-items: center; justify-content: center; font-size: 2rem; font-weight: bold; color: #94a3b8;">
                {{ substr($recipientName ?? 'U', 0, 1) }}
            </div>
        @endif
    </div>

    <div class="sidebar-section">
        <h2>Contact</h2>
        <div style="font-size: 0.8rem; line-height: 1.6; display: flex; flex-direction: column; gap: 10px;">
            @if(!empty($contactInfo['email'])) 
                <div>
                    <strong style="display:block; font-size:0.7rem; text-transform:uppercase; color:#94a3b8;">Email</strong>
                    <span style="word-break: break-all;">{{ $contactInfo['email'] }}</span>
                </div> 
            @endif
            @if(!empty($contactInfo['phone'])) 
                <div>
                    <strong style="display:block; font-size:0.7rem; text-transform:uppercase; color:#94a3b8;">Phone</strong>
                    <span>{{ $contactInfo['phone'] }}</span>
                </div> 
            @endif
            @if(!empty($contactInfo['location'])) 
                <div>
                    <strong style="display:block; font-size:0.7rem; text-transform:uppercase; color:#94a3b8;">Address</strong>
                    <span>{{ $contactInfo['location'] }}</span>
                </div> 
            @endif
            @if(!empty($contactInfo['website'])) 
                <div>
                    <strong style="display:block; font-size:0.7rem; text-transform:uppercase; color:#94a3b8;">Link</strong>
                    <a href="{{ $contactInfo['website'] }}" target="_blank" style="color: {{ $brandColor }}; font-weight: 600;">{{ $contactInfo['website'] }}</a>
                </div> 
            @endif
        </div>
    </div>

    @if(!empty($personalInfo) && array_filter($personalInfo))
    <div class="sidebar-section">
        <h2>Professional Info</h2>
        <div style="font-size: 0.8rem; line-height: 1.6; display: grid; grid-template-columns: 1fr; gap: 8px;">
            @foreach(['Age' => 'age', 'Date of Birth' => 'dob', 'Gender' => 'gender', 'Civil Status' => 'civil_status', 'Nationality' => 'nationality', 'Religion' => 'religion', 'Height' => 'height', 'Weight' => 'weight'] as $label => $key)
                @if(!empty($personalInfo[$key]))
                    <div style="display: flex; justify-content: space-between; border-bottom: 1px dashed #e2e8f0; padding-bottom: 2px;">
                        <span style="color: #64748b; font-weight: 500;">{{ $label }}:</span>
                        <span style="font-weight: 600; text-transform: uppercase;">{{ $personalInfo[$key] }}</span>
                    </div>
                @endif
            @endforeach
            
            @if(!empty($personalInfo['place_of_birth']))
                <div style="margin-top: 5px;">
                    <span style="color: #64748b; font-weight: 500; display: block;">Place of Birth:</span>
                    <span style="font-weight: 600; text-transform: uppercase;">{{ $personalInfo['place_of_birth'] }}</span>
                </div>
            @endif

            @if(!empty($personalInfo['languages']))
                <div style="margin-top: 5px;">
                    <span style="color: #64748b; font-weight: 500; display: block;">Languages:</span>
                    <span style="font-weight: 600; text-transform: uppercase;">{{ $personalInfo['languages'] }}</span>
                </div>
            @endif
        </div>
    </div>
    @endif

    <div class="sidebar-section" style="margin-top: auto; opacity: 0.6; font-size: 0.7rem;">
        <p>Generated by ArchitectAI</p>
    </div>
</div>

<div class="cv-main">
    <div class="cv-header">
        <h1>{{ $recipientName ?? 'Candidate Name' }}</h1>
        <div class="role">{{ $recipientTitle ?? 'Professional Role' }}</div>
    </div>

    <div class="cv-body">
        {!! $content !!}
    </div>
</div>
